### ISSUE TITLE
如何在bucket中用代码创建文件夹？

### ISSUE THREAD

**Issue by mdjwanghong** [tencentyun/qcloud-sdk-ios-samples#2]
如何在bucket中用代码创建文件夹？

**Comment by EricCheungSCUT** [comment]
Hi, mdjwanghong
目前在XML的SDK中是**没有直接创建文件夹的接口**的，如果想通过XML SDK来实现创建文件夹的需求的话，可以在上传文件时，将request的object填成 [bucket]/[object name]的形式。    
       
举个例子，如果我想向名为Tencent的Bucket中，创建一个叫Test的文件夹，并且在里面上传名为picture.jpg的图片，那么可以构建这样的一个请求
```objective-c
    QCloudCOSXMLUploadObjectRequest* put = [QCloudCOSXMLUploadObjectRequest new];
     put.object = @"Test/picture.jpg"; 
     put.bucket = @"Tencent"
     put.body = /* file url */
    [[QCloudCOSTransferMangerService defaultCOSTRANSFERMANGER] UploadObject:put];
```

**Comment by mdjwanghong** [comment]
你好，谢谢！
我看文档说，不建议使用JSON版本的SDK，建议使用XML版本的，但XML版本的接口非常少，请问将来是否会提供更丰富的接口？
我如果想移动、删除文件或者删除、合并文件夹等常规操作，能否提供文档，谢谢！

**Comment by EricCheungSCUT** [comment]
首先我们是推荐使用最新的XML 版本的SDK。

其次是其实XML SDK提供的接口并不少，恰恰相反可以看到XML SDK的接口是要比JSON SDK要多的，特别是在对Bucket进行操作的接口上。这里我非常肯定的说，对于XML SDK我们在不断地丰富功能，提供更多的接口。

目前我们暂未提供移动文件和对文件夹进行操作的接口，至于删除文件是有的，可以参照文档https://github.com/tencentyun/qcloud-sdk-ios/tree/master/QCloudCOSXML中，删除单个对象或者删除多个对象一章。或者可以参照代码注释和我们附带的单元测试中的例子来进行操作。
