### ISSUE TITLE
请规范一下您的 Coding Style 可以吗？乱成这样怎么看？

### ISSUE THREAD

**Issue by wangleiTT** [tencentyun/qcloud-sdk-ios-samples#4]
人格分裂的一样的源码和 demo，作为大厂对于自己的代码风格完全不 care 的么？

`- (NSDictionary*)filterHeaders; {
// 声明还来个分号？
}`

`-(void)PutRequestWithUrl:(NSString *)urlString request:(NSMutableURLRequest* )urlRequest successBlock:(SuccessBlock)success;
{
// 方法名大写？- (void)空格没有？结尾还来个分号？
}`

`- (void)setUpContent{
// setup 一个单词强行来个驼峰 setUp，我一眼看过去以为你们是在重写 upContent 这个 property 的 set 方法。
}`

类似的代码项目中到处都是，如果你们想做好这块产品，请尊重一下开发者，用点心。

**Comment by 15809284891** [comment]
已更新

**Comment by 15809284891** [comment]
感谢吐槽，以后一定严加规范，您反馈的问题已修复，请更新最新版的代码

**Comment by 15809284891** [comment]
已更新
